# Future expansion (multi-day runs, filters, etc.)
# Two-space indentation per preference
url: https://raw.githubusercontent.com/dp247/Freeview-EPG/master/epg.xml
start: 1759449600 # 2025-10-03 00:00:00 UTC
output_dir: docs
